# Generated by Django 4.1.4 on 2022-12-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.CharField(default='Email', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='Phone',
            field=models.CharField(default='Phone', max_length=200),
        ),
    ]
