# Generated by Django 4.1.4 on 2022-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Commodity',
            field=models.CharField(default='Commodity', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='Date',
            field=models.CharField(default='Destination', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='Destination',
            field=models.CharField(default='Destination', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='Origin',
            field=models.CharField(default='Origin', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='First Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=200),
        ),
    ]
